INSERT INTO DEPARTMENT VALUES(101,'Computer Science');
INSERT INTO DEPARTMENT VALUES(102,'Electronics');
INSERT INTO STUDENT VALUES(1,'Harish',102);
INSERT INTO STUDENT VALUES(2,'Murali',101);
INSERT INTO STUDENT VALUES(3,'Sumanth',101);